/*

 PLAYERSPRITES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 16 x 16
  Tiles                : 0 to 24

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : 1 Byte per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __playerSprites_h_INCLUDE
#define __playerSprites_h_INCLUDE

/* Bank of tiles. */
#define playerSpritesBank 0

/* Super Gameboy palette 0 */
#define playerSpritesSGBPal0c0 6076
#define playerSpritesSGBPal0c1 8935
#define playerSpritesSGBPal0c2 6596
#define playerSpritesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define playerSpritesSGBPal1c0 6076
#define playerSpritesSGBPal1c1 8935
#define playerSpritesSGBPal1c2 6596
#define playerSpritesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define playerSpritesSGBPal2c0 6076
#define playerSpritesSGBPal2c1 8935
#define playerSpritesSGBPal2c2 6596
#define playerSpritesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define playerSpritesSGBPal3c0 6076
#define playerSpritesSGBPal3c1 8935
#define playerSpritesSGBPal3c2 6596
#define playerSpritesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define playerSpritesCGBPal0c0 31614
#define playerSpritesCGBPal0c1 25150
#define playerSpritesCGBPal0c2 2207
#define playerSpritesCGBPal0c3 0

/* Gameboy Color palette 1 */
#define playerSpritesCGBPal1c0 31576
#define playerSpritesCGBPal1c1 32421
#define playerSpritesCGBPal1c2 23968
#define playerSpritesCGBPal1c3 0

/* Gameboy Color palette 2 */
#define playerSpritesCGBPal2c0 14303
#define playerSpritesCGBPal2c1 543
#define playerSpritesCGBPal2c2 10015
#define playerSpritesCGBPal2c3 0

/* Gameboy Color palette 3 */
#define playerSpritesCGBPal3c0 21461
#define playerSpritesCGBPal3c1 8935
#define playerSpritesCGBPal3c2 6596
#define playerSpritesCGBPal3c3 0

/* Gameboy Color palette 4 */
#define playerSpritesCGBPal4c0 31447
#define playerSpritesCGBPal4c1 31764
#define playerSpritesCGBPal4c2 20500
#define playerSpritesCGBPal4c3 0

/* Gameboy Color palette 5 */
#define playerSpritesCGBPal5c0 32767
#define playerSpritesCGBPal5c1 31707
#define playerSpritesCGBPal5c2 14625
#define playerSpritesCGBPal5c3 0

/* Gameboy Color palette 6 */
#define playerSpritesCGBPal6c0 6076
#define playerSpritesCGBPal6c1 8935
#define playerSpritesCGBPal6c2 6596
#define playerSpritesCGBPal6c3 0

/* Gameboy Color palette 7 */
#define playerSpritesCGBPal7c0 6076
#define playerSpritesCGBPal7c1 8935
#define playerSpritesCGBPal7c2 6596
#define playerSpritesCGBPal7c3 0
/* CGBpalette entries. */
extern const unsigned char playerSpritesCGB[];
/* Start of tile array. */
extern const unsigned char playerSprites[];

#endif

/* End of PLAYERSPRITES.H */
