/*

 HOME_TOWN.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 100 x 100
   Tile set      : Z:\Users\skyewaddell\Documents\github\gameboy-games\test game\maps\home_town.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __home_town_h_INCLUDE
#define __home_town_h_INCLUDE

#define homeTownMapWidth 100
#define homeTownMapHeight 100
#define homeTownMapBank 0

extern const unsigned char homeTownMap[];

#endif

/* End of HOME_TOWN.H */
